version: "3"

services:
  app-server:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
      args:
        app_env: development
        app_port: ${FLASK_RUN_PORT}
    command: python app.py
    container_name: app-server
    restart: always
    volumes:
      - ./:/app
    ports:
      - "${FLASK_RUN_PORT}:${FLASK_RUN_PORT}"
    expose:
      - ${FLASK_RUN_PORT}
    links:
      - app-db
  app-db:
    container_name: app-db
    image: mongo
    ports:
      - "30000:27017"
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
      driver: local
