name: Code Validation

on:
  pull_request:
    branches:
      - main
      - staging
      - production

jobs:
  security-check:
    env:
      TARGET_COMMIT: ${{ github.base_ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install and run bandit linter
        run: |
          files=$(git diff --diff-filter=d --name-only origin/$TARGET_COMMIT..HEAD | grep "\.py$" || true)
          if [ -n "$files" ];then pip3 install bandit;else exit 0; fi
          excludes="tests/\|encryption/benchmarks/"
          bandit -v -x $excludes -iii -lll $files
  black-check:
    env:
      TARGET_COMMIT: ${{ github.base_ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install and run black
        run: |
          changed_python_files=$(git diff --diff-filter=d --name-only origin/$TARGET_COMMIT..HEAD | grep "\.py$" | grep -vE "config|examples|fabfile|manage.py|migrations|venv|build" | tr '\n' ' ' || true)
          if [ -n "$changed_python_files" ];then pip3 install black;else exit 0; fi
          black --check -v --config ${{ github.workspace }}/pyproject.toml $changed_python_files
  isort-check:
    env:
      TARGET_COMMIT: ${{ github.base_ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install and run isort
        run: |
          changed_python_files=$(git diff --diff-filter=d --name-only origin/$TARGET_COMMIT..HEAD | grep "\.py$" | grep -vE "config|examples|fabfile|manage.py|migrations|venv|build|__init__.py" | tr '\n' ' ' || true)
          if [ -n "$changed_python_files" ];then pip3 install isort;else exit 0; fi
          isort -v --check --profile black --settings-path ${{ github.workspace }}/pyproject.toml --atomic $changed_python_files
